   
regex_patterns = {
    "MySQL":[
    r'SQL syntax.*?MySQL',
    r'Warning.*?\Wmysqli?_',
    r'MySQLSyntaxErrorException',
    r'valid MySQL result',
    r'check the manual that (corresponds to|fits) your MySQL server version',
    r'check the manual that (corresponds to|fits) your MariaDB server version',
    r'check the manual that (corresponds to|fits) your Drizzle server version',
    r"Unknown column '[^ ]+' in 'field list'",
    r'MySqlClient\.',
    r'com\.mysql\.jdbc',
    r'Zend_Db_(Adapter|Statement)_Mysqli_Exception',
    r'Pdo[./_\\]Mysql',
    r'MySqlException',
    r'SQLSTATE\[\d+\]: Syntax error or access violation',
    r'MemSQL does not support this type of query',
    r'is not supported by MemSQL',
    r'unsupported nested scalar subselect'
    ],
    "Oracle":[
        r'ORA-\d{5}',
        r'Oracle error',
        r'Oracle.*?Driver',
        r'Warning.*?\W(oci|ora)_',
        r'quoted string not properly terminated',
        r'SQL command not properly ended',
        r'macromedia\.jdbc\.oracle',
        r'oracle\.jdbc',
        r'Zend_Db_(Adapter|Statement)_Oracle_Exception',
        r'Pdo[./_\\](Oracle|OCI)',
        r'OracleException'
        ],
    "PostgreSQL":[
        r'PostgreSQL.*?ERROR',
        r'Warning.*?\Wpg_',
        r'valid PostgreSQL result',
        r'Npgsql\.',
        r'PG::SyntaxError:',
        r'org\.postgresql\.util\.PSQLException',
        r'ERROR:\s\ssyntax error at or near',
        r'ERROR: parser: parse error at or near',
        r'PostgreSQL query failed',
        r'org\.postgresql\.jdbc',
        r'Pdo[./_\\]Pgsql',
        r'PSQLException'
    ],
    "Microsoft SQL Server":[
        r'Driver.*? SQL[\-\_\ ]*Server',
        r'OLE DB.*? SQL Server',
        r'\bSQL Server[^&lt;&quot;]+Driver',
        r'Warning.*?\W(mssql|sqlsrv)_',
        r'\bSQL Server[^&lt;&quot;]+[0-9a-fA-F]{8}',
        r'System\.Data\.SqlClient\.(SqlException|SqlConnection\.OnError)',
        r'(?s)Exception.*?\bRoadhouse\.Cms\.',
        r"Microsoft SQL Native Client error '[0-9a-fA-F]{8}",
        r'\[SQL Server\]',
        r'ODBC SQL Server Driver',
        r'ODBC Driver \d+ for SQL Server',
        r'SQLServer JDBC Driver',
        r'com\.jnetdirect\.jsql',
        r'macromedia\.jdbc\.sqlserver',
        r'Zend_Db_(Adapter|Statement)_Sqlsrv_Exception',
        r'com\.microsoft\.sqlserver\.jdbc',
        r'Pdo[./_\\](Mssql|SqlSrv)',
        r'SQL(Srv|Server)Exception',
        r'Unclosed quotation mark after the character string',
    ],
    "Microsoft Access":[
        r'Microsoft Access (\d+ )?Driver',
        r'JET Database Engine',
        r'Access Database Engine',
        r'ODBC Microsoft Access',
        r'Syntax error \(missing operator\) in query expression',
    ],
    
    }